### ISSUE TITLE
Users Windel/name2 broken.

### ISSUE THREAD

**Issue by jagr0399** [polivilas/EmuTarkov#10]
on the windel account Whenever i go buy something the server.bat crashes and on name2 it isnt logging in,

**Comment by jagr0399** [comment]
https://gyazo.com/429cfdaedde3e5075d61f7ac894ec7b4 this is what windel shows when you buy something

**Comment by panicco** [comment]
Accounts are for Maoci build. Some have item id errors, Copy Clear account and rename to build your own.
default emu tarkov build has no accounts yet that im aware.

**Comment by polivilas** [comment]
I have no idea what 'accounts' you are talking about. EmuTarkov doesn't have any support for multiple accounts.
