### ISSUE TITLE
Rig duplication bug

### ISSUE THREAD

**Issue by InNoHurryToCode** [polivilas/EmuTarkov#26]
The original report can be found [here](https://www.unknowncheats.me/forum/2482850-post160.html).

## What happens
The rig duplicates and layout screws ups in a raid happen when I buy stacks of items that are 
bigger than the officially accepted size.

## How to replicate
1. buy stacks of item that are bigger than the officially accepted size.
2. equip the item.
3. start a new raid with a rig equipped.
4. open the inventory.
5. move the rig.
6. open the inventory again. There should be 2 rigs now. 

## Workaround
Split the stacks to the officially accepted size.

**Comment by InNoHurryToCode** [comment]
## Affected versions
This seems to exist in before I commited code, so I assume this bug is present in pretty much in all older versions of the code.

## Fix suggestion
Add additional functionality to confirmTrade() in item.js to deal with too large stacks.
Add additional functionality to mergeItem() in item.js to deal with too large stacks.

**Comment by polivilas** [comment]
Doesn't https://github.com/polivilas/EmuTarkov/blob/master/src/item.js#L278 take care of it?

**Comment by InNoHurryToCode** [comment]
Tested it, it does sort of but not PvE as far as I noticed (need more testing, my result might be an isolated case). 

When I enter an item quantity higher than the stack allows, I get only as much as the stack allows.
So if I buy 1000 bullets for example, I woud get only 40.
