### ISSUE TITLE
The wiki does not work

### ISSUE THREAD

**Issue by Edi-Gaming** [polivilas/EmuTarkov#31]
The link to the wiki is a 404 page

**Comment by Edi-Gaming** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40004403/60543006-458eb380-9ce3-11e9-8140-b20d8ba178b2.gif)

**Comment by crynov3** [comment]
it got taken down

**Comment by Edi-Gaming** [comment]
Why? By git hub or the creator

**Comment by crynov3** [comment]
dunno

**Comment by themaoci** [comment]
by a creator cause strange activity on our team github's

you can check "justemutarkov" for more info ;)

**Comment by Edi-Gaming** [comment]
Thank you! Closed.
