### ISSUE TITLE
tarkov alpha problem

### ISSUE THREAD

**Issue by crynov3** [polivilas/EmuTarkov#32]
when using the retro build for alpha the game starts local game forever

**Comment by Edi-Gaming** [comment]
What do you mean "Retro Build" Can you please give more detail? As for the alpha build this emulator is not built to work on the alpha build only on the beta build.

**Comment by crynov3** [comment]
> What do you mean "Retro Build" Can you please give more detail? As for the alpha build this emulator is not built to work on the alpha build only on the beta build.

there are two branches the main branch for the latest version and the retro branch for the alpha version

**Comment by Edi-Gaming** [comment]
What do you mean "the game starts local game forever"?

**Comment by crynov3** [comment]
> What do you mean "the game starts local game forever"?

it creates the game world then loads the map then it just says "starting local game"

**Comment by Edi-Gaming** [comment]
Are you running it through offline raid mode? because the non-offline is not functional yet

**Comment by polivilas** [comment]
Alpha requires patched assembly, because something is fucked with quests.
Link for 0.1.0.1001 and 0.1.0.1002:
https://puu.sh/Haufb/c6a643ddb1.dll
Link for 0.1.0.1191:
https://puu.sh/DOkkd/637e757e2d.dll

Rename to Assembly-CSharp.dll, overwrite the old one, enjoy.

**Comment by crynov3** [comment]
> Alpha requires patched assembly, because something is fucked with quests.
> Link for 0.1.0.1001 and 0.1.0.1002:
> https://puu.sh/DOkj4/ab6fd0f871.dll
> Link for 0.1.0.1191:
> https://puu.sh/DOkkd/637e757e2d.dll
> 
> Rename to Assembly-CSharp.dll, overwrite the old one, enjoy.

is it only the map dust2 or can it also be factory?

**Comment by polivilas** [comment]
Modify locations for other maps.

**Comment by themaoci** [comment]
@crynov3 you need to change file format from txt to json and replace
1 develop map
2 dust2 map
3 factory map
i dont know if its working jsut writed it down ;)
[locations.json.txt](https://github.com/polivilas/EmuTarkov/files/3485890/locations.json.txt)

**Comment by kaleka1337** [comment]
> Alpha requires patched assembly, because something is fucked with quests. Link for 0.1.0.1001 and 0.1.0.1002: https://puu.sh/Haufb/c6a643ddb1.dll Link for 0.1.0.1191: https://puu.sh/DOkkd/637e757e2d.dll
> 
> Rename to Assembly-CSharp.dll, overwrite the old one, enjoy.

The link is not working

**Comment by Gorbino2003** [comment]
> Alpha requires patched assembly, because something is fucked with quests. Link for 0.1.0.1001 and 0.1.0.1002: https://puu.sh/Haufb/c6a643ddb1.dll Link for 0.1.0.1191: https://puu.sh/DOkkd/637e757e2d.dll
> 
> Rename to Assembly-CSharp.dll, overwrite the old one, enjoy.

I understand that this is an old thread, but what do you specifically mean by something was fucked with the quest?
