### ISSUE TITLE
Critical error receiving profile data

### ISSUE THREAD

**Issue by dieselpower1** [polivilas/EmuTarkov#44]
New profile, map: plant, at 3rd raid sucsessfull escaped, then this error, see screenshot

![EscapeFromTarkov 2019-09-25 14-43-44-48](https://user-images.githubusercontent.com/46282234/65604541-54b69200-dfb0-11e9-97e1-4ca919713f6e.jpg)

attach my profile
[2.zip](https://github.com/polivilas/EmuTarkov/files/3652667/2.zip)

**Comment by polivilas** [comment]
Hey, this is EmuTarkov, not JustEmuTarkov, I can't help you with your problem, you should head over there instead.
https://github.com/justemutarkov/EmuTarkov-Server
