### ISSUE TITLE
Custom Map & Private Server

### ISSUE THREAD

**Issue by Zibbp** [polivilas/EmuTarkov#5]
I saw the custom map demo you published, amazing work. With custom maps are you planning to implement a private server? And was the map just made in Unity?

**Comment by themaoci** [comment]
@zippy4 all maps is made in unity by BSG he just reveal the hidden content for private server its alot of work to be done rly but its possible

**Comment by Dood9123** [comment]
will you or polivilas be working on private server or are you leaving that for others?

**Comment by polivilas** [comment]
Regarding map - maoci nailed it - it is just a leftover map in old alphas - regarding private servers - I don't plan on doing anything in that regard.

**Comment by InNoHurryToCode** [comment]
@polivilas since this issue is answered already and the readme now mentions that you've no intentions of making this a private server, you might wanna close this.
