### ISSUE TITLE
Issue to install

### ISSUE THREAD

**Issue by iL33T** [polivilas/EmuTarkov#7]
that's the run.bat
![image](https://user-images.githubusercontent.com/49046681/55200354-8505ab00-519c-11e9-995e-8459380dafab.png)

**Comment by panicco** [comment]
Are you running the install.bat first?

**Comment by iL33T** [comment]
yep

**Comment by panicco** [comment]
Either you don't have node js installed or you may have corrupt files. Re download.

**Comment by iL33T** [comment]
i have installed the node, and downloaded again the files... same error

**Comment by iL33T** [comment]
gonna try update the java

**Comment by panicco** [comment]
It's seems to be an issue with the modules in Js. So I was going to suggest the same. Or a reinstall of node. Good luck.

**Comment by iL33T** [comment]
![image](https://user-images.githubusercontent.com/49046681/55201243-ddd74280-51a0-11e9-9d02-624c7bfcbe34.png)
uptade the java doesn't work, now gonna try to reinstall the node. Thanks for your help

**Comment by iL33T** [comment]
same error -_-

**Comment by polivilas** [comment]
Start the game first - it needs to generate the registry entries to spoof the launcher check.

**Comment by iL33T** [comment]
this is what i don't understand... how i can have the game files?

**Comment by iL33T** [comment]
that's just a emulator to peoples that buy the game, play offline?

**Comment by panicco** [comment]
Yes. This emulates the traders and invertory back end and some other things. It requires the game to use it.

**Comment by panicco** [comment]
Doesn't require you to buy the game because it emulates the login as well.

**Comment by iL33T** [comment]
right, so if i don't have to buy the game, but need to install the game before install the emulator, how i gonna do it? how i gonna install the game?

**Comment by panicco** [comment]
Sorry. I'm not sure if this is the right place for you to figure that part out. Creator can help further. Or Google.

**Comment by iL33T** [comment]
![image](https://user-images.githubusercontent.com/49046681/55255578-c1d3af80-5239-11e9-9f08-4e53d90b8f44.png)
I downloaded the game, started it and tryed again to install the emulator... Same error

**Comment by InNoHurryToCode** [comment]
Hey @iL33T 

If you do all the following steps correctly, the game will work.

[EDIT] check the new readme file with the instructions.

**Comment by InNoHurryToCode** [comment]
@polivilas pretty sure that this issue can be closed.
