### ISSUE TITLE
Install.bat not working keeps closing on itself.

### ISSUE THREAD

**Issue by jagr0399** [polivilas/EmuTarkov#9]
i dont know if im doing this correctly but everytime i double click on install it just closes it self and i dont know if i need node.js to run it but idk where to get it.

**Comment by jagr0399** [comment]
new problem. https://gyazo.com/a0d60256e810f10aca7f777b02b1b748
that screenshot shows what i get when i double click on install when i put it on a cmd but normally it will just close itself after it downloads something the next one to it is the RUN bat so how do i fix?

**Comment by panicco** [comment]
Your missing files, as you can see in your screenshot package.json is missing.

**Comment by jagr0399** [comment]
> Your missing files, as you can see in your screenshot package.json is missing.

so where do i get that json file?

**Comment by panicco** [comment]
It is included in emutarkov. Your download may have been corrupt or missing files. Delete all and redownload. I also recommend GitHub desktop to keep files in sync.

**Comment by jagr0399** [comment]
> It is included in emutarkov. Your download may have been corrupt or missing files. Delete all and redownload. I also recommend GitHub desktop to keep files in sync.

ok thank you

**Comment by jagr0399** [comment]
> It is included in emutarkov. Your download may have been corrupt or missing files. Delete all and redownload. I also recommend GitHub desktop to keep files in sync.

i downloaded the file in github desktop and it keeps on closing on itself is there anyway like discord to contact you faster?

**Comment by jagr0399** [comment]
Also its saying that im missing package.json but the json file is right there. does antivirus have to do anything with it?

**Comment by jagr0399** [comment]
> It is included in emutarkov. Your download may have been corrupt or missing files. Delete all and redownload. I also recommend GitHub desktop to keep files in sync.

everytime i run the install bat it will pop up with an installing thing and then half way it closes
i just want to try this out please get back to me ASAP.

**Comment by jagr0399** [comment]
also what does it mean by package locked? everytime i ran the bat i get a package lock.

**Comment by panicco** [comment]
Download
place in tarkov folder
Install node.js
Run install.bat (will flash text then close)
Start run.bat
Edit client.config
Run tarkov
(Do not run as admin)

**Comment by jagr0399** [comment]
> Download
> place in tarkov folder
> Install node.js
> Run install.bat (will flash text then close)
> Start run.bat
> Edit client.config
> Run tarkov
> (Do not run as admin)

ok i did that i put all of the things in tarkov folder but still getting error thats it fucked

**Comment by jagr0399** [comment]
> > Download
> > place in tarkov folder
> > Install node.js
> > Run install.bat (will flash text then close)
> > Start run.bat
> > Edit client.config
> > Run tarkov
> > (Do not run as admin)
> 
> ok i did that i put all of the things in tarkov folder but still getting error thats it fucked

and a package lock.json
so how do i fix?

**Comment by panicco** [comment]
Like I said your best bet is to delete all files. And start from scratch.
What version of game are you using?
Have you installed node.js?

**Comment by panicco** [comment]
Package.lock is generated at successful install.

**Comment by jagr0399** [comment]
> Like I said your best bet is to delete all files. And start from scratch.
> What version of game are you using?
> Have you installed node.js?

well i delete everything that has do with anything with it and yes i have node.js thats how im able to open the bat file. if you can can i add you on discord or add mine jagr034#8267 to get this problem fixed faster?

**Comment by jagr0399** [comment]
whhttps://gyazo.com/5e9c7d219ab15d60126c62a38e539b5c?token=9e431d2a2b2e1ad083007d8ec93237de this is when i run  the run.bat file
